/*
 *  Assignment II for BusStation
 *  Team members : Muhammad Ibrahim, Hossam tarek, Sherif ahmed
 */
package forms;

import java.awt.Toolkit;
import material.Tickets;

/**
 *
 * @author Muhammad
 */
public class ShowTicket extends javax.swing.JFrame {

    /**
     * Creates new form ShowTicket
     */
    public ShowTicket(Tickets ticket) {
        initComponents(); fromField.setText(ticket.getMyTrip().getFrom());
        toField.setText(ticket.getMyTrip().getTo());
        nameField.setText(ticket.getPassenger().getName());
        nationalIdField.setText(ticket.getPassenger().getNationalId());
        dateField.setText(ticket.getMyTrip().getDay() + "/"
                + ticket.getMyTrip().getMonth()
                + "/" + ticket.getMyTrip().getYear());
        setTitle("Show Ticket");
        setIconImage(Toolkit.getDefaultToolkit().getImage("E:\\Programming\\EmployeeProject(bata)\\image.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nationalIdField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fromField = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        toField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setText("my from");

        jLabel7.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        jLabel7.setText("Date :");

        dateField.setText("my from");

        jLabel8.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        jLabel8.setText("NaID :");

        nationalIdField.setText("my dest");

        jLabel1.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        jLabel1.setText("From :");

        fromField.setText("my from");

        jLabel4.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        jLabel4.setText("Dest :");

        toField.setText("my dest");

        jLabel5.setFont(new java.awt.Font("Titillium Web", 1, 14)); // NOI18N
        jLabel5.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Your Trip Ticket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(fromField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(31, 31, 31)
                                .addComponent(nationalIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(toField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromField)
                    .addComponent(jLabel4)
                    .addComponent(toField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameField)
                    .addComponent(jLabel8)
                    .addComponent(nationalIdField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dateField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateField;
    private javax.swing.JLabel fromField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel nationalIdField;
    private javax.swing.JLabel toField;
    // End of variables declaration//GEN-END:variables
}
